using Avalonia;
using Avalonia.Controls;
using Avalonia.Markup.Xaml;
using Avalonia.Media;

namespace NP.Demos.StaticVsDynamicXamlResourcesSample
{
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
#if DEBUG
            this.AttachDevTools();
#endif
            // Button button = this.FindControl<Button>("ChangeStatusButton");
            // button.Click += Button_Click;

            // ChangeStatusButton is generated by Avalonia code generator
            ChangeStatusButton.Click += Button_Click;
        }

        private void Button_Click(object? sender, Avalonia.Interactivity.RoutedEventArgs e)
        {
            // getting a Window resource by its name
            var statusBrush = this.FindResource("StatusBrush");

            // setting the window resource to a new value
            this.Resources["StatusBrush"] = 
                             new SolidColorBrush(Colors.Red);
        }

        // If you use Avalonia code generator, be sure to use the generated one (containing the definition of objects in the GUI)
        //
        //private void InitializeComponent()
        //{
        //    AvaloniaXamlLoader.Load(this);
        //}
    }
}
